services:
  cs2-medal-parser:
    image: ghcr.io/awhare-club/cs-medal-parser:latest
    # build: .
    container_name: cs-medal-parser
    volumes:
      - ./data/:/app/data/
    environment:
      PYTHONUNBUFFERED: "1"
      CS_MEDAL_MAX_WORKERS: "10"
    restart: unless-stopped
